### ISSUE TITLE
Plans for Swift 6 concurrency?

### ISSUE THREAD

**Issue by dginsburg** [hotwired/hotwire-native-ios#30]
Do you have plans to make Turbo iOS compliant with Swift 6 concurrency? It's difficult (maybe impossible) right now to use Turbo as a dependency in an app that is enforcing the concurrency rules.

**Comment by olivaresf** [comment]
Swift 6's strict concurrency is quite new, so we don't have specific plans to implement it yet. It's definitely something that will come up sooner rather than later, though, so it's on our radar.

**Comment by dginsburg** [comment]
If I were to submit a PR that added the concurrency support, would you consider it and merge if it met your standards?

I'm haven't looked into how much work it is, but I don't want to be on a private fork or do the work to make it a PR if it's not likely to be accepted.

**Comment by olivaresf** [comment]
Thanks for offering! Unfortunately, we're not ready to commit to implementing Swift concurrency in the near future, so we would not consider a PR that added concurrency support.
