### ISSUE TITLE
Add allowsLinkPreview as a config option?

### ISSUE THREAD

**Issue by samuelmolinari** [hotwired/hotwire-native-ios#34]
I can't figure out how to set `allowsLinkPreview = false` on the webView handled by the sessions created by the `Navigator` class.

Ideally, I would love to be able to do the following:

```swift
let navigator = Navigator(pathConfiguration: pathConfiguration, delegate: self)
navigator.session.webView.allowsLinkPreview = false
navigator.modalSession.webView.allowLinkPreview = false
```

But this isn't possible at the moment as both `session` and `modalSession` are internal variables.

I feel like most devs who use Hotwire Native will prefer to have `allowsLinkPreview` set to false by default, or at least have it as a config option that will be applied to all web views.

Or am I missing an obvious, simple way to disable the link preview when the user long press on a link 🤔

**Comment by MichalSznajder** [comment]
Use `Hotwire.config.makeCustomWebView` to create customize web view:

```
Hotwire.config.makeCustomWebView = { config in    
    let webView = WKWebView(frame: .zero, configuration: config)
    webView.allowsLinkPreview = false
    webView.scrollView.bounces = false
               
    return webView
}
```

**Comment by samuelmolinari** [comment]
@MichalSznajder Thank you, that's exactly what I was looking for!

**Comment by samuelmolinari** [comment]
Solved
