### ISSUE TITLE
hotwire native and css view-transitions ?

### ISSUE THREAD

**Issue by aktxyz** [hotwired/hotwire-native-ios#38]
It looks like view transitions are not working with ios/turbo ... I am not sure if this is a turbo thing or webview thing (probably webview).

I followed this example and the view-transitions with turbo web look great (as long as you turn it on in chrome config !!).
https://dev.to/nejremeslnici/how-to-use-view-transitions-in-hotwire-turbo-1kdi

But the transitions do not work in turbo native ... any ideas ?

**Comment by MichalSznajder** [comment]
I think they will not work. Between navigation WebView is detached and reattached. You have to implement any transitions yourself in native code.

**Comment by aktxyz** [comment]
Yes ... I have actually modified the code to not detach the webview ... I was wanting to see if the css-view-transition approach would work. I think the detach/reattach thing is mainly to help with jank on page navs? if so, it seems like the css-view-transition could be a simpler alternative perhaps?

**Comment by olivaresf** [comment]
Hey @aktxyz 👋🏻,

Like Michal said, it's unlikely view-transitions will work due to the way we handle native navigation, but I'm happy to take a look if you can share a web demo.
