### ISSUE TITLE
native.hotwired.dev seems down to me

### ISSUE THREAD

**Issue by bhavinNandani** [hotwired/hotwire-native-ios#66]
### Description

The Native Hotwired website (`native.hotwired.dev`) is currently unreachable. I am encountering the following error:

- **Error**: `ERR_NAME_NOT_RESOLVED`
- **Message**: "This site can’t be reached. The server's IP address could not be found."

### Steps to Reproduce
1. Visit the website: [native.hotwired.dev](http://native.hotwired.dev)
2. See the error: `ERR_NAME_NOT_RESOLVED`

### Expected Behavior
The site should load and resolve the domain to the correct IP address.

### Screenshot
![Screenshot 2024-12-24 at 3 09 42 PM](https://github.com/user-attachments/assets/7b24fd33-083f-41f3-b93e-27d503625f39)

### Additional Information
- Browser: Chrome
- OS: Mac

There may be an issue with DNS resolution for this domain. Please check the DNS settings or server status.

Thanks for looking into this!

**Comment by joemasilotti** [comment]
Looks like this was resolved. I'm not sure what happened but thanks for reporting!
